---
# handlers/main.yml for windows_cert_crawler_install_config_with_pwd

- name: log_collect_certs_with_pwd
  win_shell: |
    $timestamp = Get-Date -Format "MM/dd HH:mm:ss"
    Add-Content -Path "{{ cc_path }}playbook_runtime.log" -Value "$timestamp INFO   :...cert_collector: file path scan completed, certificates with passwords collected"

- name: log_config_crawler_with_pwd
  win_shell: |
    $timestamp = Get-Date -Format "MM/dd HH:mm:ss"
    Add-Content -Path "{{ cc_path }}playbook_runtime.log" -Value "$timestamp INFO   :...config_generator: encryption arguments prepared for password-protected certificates"
