---
# handlers/main.yml for windows_cert_crawler_install_start

- name: log_start_crawler
  win_shell: |
    $timestamp = Get-Date -Format "MM/dd HH:mm:ss"
    Add-Content -Path "{{ cc_path }}playbook_runtime.log" -Value "$timestamp INFO   :...execution_engine: certificate processing completed successfully"
